// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJdaHXAA580ZUAf85zmznUt7BvKa1vmWQ',
    appId: '1:1064846149599:android:7495c235c4824e43a0e66a',
    messagingSenderId: '801046060474',
    projectId: 'flutter-blog-9763b',
    authDomain: 'flutter-blog-9763b.firebaseapp.com',
    storageBucket: 'flutter-blog-9763b.appspot.com',
    measurementId: 'G-D2WVKY0ZG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OtkFdhzlZdCbuvWELwRPj9xF0ZpBdZI',
    appId: '1:1064846149599:android:7495c235c4824e43a0e66a',
    messagingSenderId: '1064846149599',
    projectId: 'testapps-1508e',
    storageBucket: 'flutter-blog-9763b.appspot.com',
  );
}
